### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by masterjg** [alex-rokabilis/nwjs-webpack-plugin#1]
For me personally this plugin does not start and crashes with this error:
```
webpack is watching the files…

listening on 62574
   14 modules
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn nw ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Here's my webpack config:
```
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const NwjsWebpackPlugin = require('nwjs-webpack-plugin');

// @ts-ignore
process.traceDeprecation = true;

const mode = process.env.NODE_ENV || 'development';
const isInDevMode = mode === 'development';

module.exports = {
  stats: 'minimal',
  externals: {
    "chrome": "chrome"
  },
  devtool: "source-map",
  mode,
  target: "node-webkit",
  entry: (() => {
    const entries = [];
    entries.push(path.resolve(__dirname, 'src/app.js'));
    return entries;
  })(),
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js',
  },
  plugins: (() => {
    const plugins = [
      new CleanWebpackPlugin([ path.resolve(__dirname, 'dist') ], {
        exclude: [ '.gitkeep' ],
        verbose: false
      }),
      new HtmlWebpackPlugin({
        template: path.resolve(__dirname, 'src/index.html'),
        filename: 'index.html'
      }),
      new CopyWebpackPlugin([
        path.resolve(__dirname, 'src/icon.png')
      ]),
      new NwjsWebpackPlugin(),
    ];
    return plugins;
  })(),
  watch: true
};
```

**Comment by noemission** [comment]
Hi! The way it works now, it expects `nw` to be available in the `$PATH`.  Meaning writing in the terminal `nw .` should spawn `nw` in the current directory. As a workaround I suggest to put the `nw` executable in `$PATH` or change the plugin's code to point to the correct executable. I am going to update the plugin to accept options like where to find `nw` and others in some days.

**Comment by masterjg** [comment]
> Hi! The way it works now, it expects nw to be available in the $PATH.  Meaning writing in the terminal nw . should spawn nw in the current directory. As a workaround I suggest to put the nw executable in $PATH or change the plugin's code to point to the correct executable. I am going to update the plugin to accept options like where to find nw and others in some days.

Anyway to make this work with https://github.com/evshiron/nwjs-builder-phoenix ? Currently I run everything with it's command `run --x64 .`

**Comment by masterjg** [comment]
P.S> if you manage to make it work with phoenix then I will finally be able to ditch webpack-dev-server in my https://github.com/masterjg/nwjs-bootstrap . Currently only way to switch between build and start (with dev-server) commands is manually editing package.json main property and that's is pretty dumb workaround in my opinion...

**Comment by noemission** [comment]
Try to change the executable path in the `runNW` function of the plugin with `node_modules/.bin/run`

**Comment by masterjg** [comment]
https://github.com/alex-rokabilis/nwjs-webpack-plugin/pull/2 fixed
