### ISSUE TITLE
Clean exit

### ISSUE THREAD

**Issue by masterjg** [alex-rokabilis/nwjs-webpack-plugin#3]
Currently I see that when we exit the nwjs app it logs crash to terminal:
```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

This needs to be fixed to have clean exit whatsoever.

**Comment by noemission** [comment]
Yes I noticed that also. Currently there is no error handling for the tcp connection serverside. We need a proper error handler so that when the `nw` app exits, the server either stays alive or closes correctly.

**Comment by masterjg** [comment]
definitely needs to close and not stay alive...

**Comment by noemission** [comment]
I think with this [change](https://github.com/alex-rokabilis/nwjs-webpack-plugin/commit/7e089d2feafbd18df6a037a4b5f10debaa907a0e#diff-168726dbe96b3ce427e7fedce31bb0bcR23) the error should not appear anymore. Although I am not sure if stopping the server when client drops is the correct way here.

**Comment by masterjg** [comment]
> I think with this change the error should not appear anymore. Although I am not sure if stopping the server when client drops is the correct way here.

Hm... is this pushed to npmjs ? Because version 0.4.0 still shows me error:
```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
NW.js app exited with 0.
```

**Comment by noemission** [comment]
Yes 0.4.0 is published in npm. I cannot reproduce this error in my app. We need to find the error stack to understand where this error is being triggered. Is it possible that these are logs from the app itself? I mean when we spawn `nw` every log is piped to this console (like the `NW.js app exited with 0`)

**Comment by masterjg** [comment]
It is plugin, because when I disable it I get normal exit:
```
Launching NW.js app...
NW.js app exited with 0.
```

Could you clone https://github.com/masterjg/nwjs-vuejs-bootstrap project and try yourself?

**Comment by noemission** [comment]
I checked your repo and I cannot reproduce the error. It exits normally with this message in the console `NW.js app exited with 0.` Also [here](https://github.com/masterjg/nwjs-vuejs-bootstrap/blob/master/webpack.config.js#L61) I don't understand how this should work. This is a whole command not the path to `nw` executable plus `run` is inside `node_modules/.bin` so I get `ENOENT`.  I had to change these stuff to make it run.

Please check that you are actually using the latest version of the plugin

**Comment by masterjg** [comment]
Just to be sure what OS are you running? I'm on windows 10. For me run works however exit throws error code...

`run . -- --load-extension=./node_modules/nw-vue-devtools/extension`
basically means start **run** script and use cwd as project root then pass to chromium vue extension.

Run script comes from https://github.com/evshiron/nwjs-builder-phoenix if that helps...

**Comment by noemission** [comment]
I am on Linux. Now `run` command is accessible because the whole process runs through `npm start`. When we run npm (or pnpm) scripts, automatically it adds `./node_modules/.bin` in `$PATH` that way `run` is actually there. I find it a bit fragile now, for example if someone runs it directly with webpack it will fail.

I suggest you to use full paths, for example `path.resolve( __dirname, './node_modules/.bin/run')` in order to be sure.

The only thing that I don't really get is why `run . -- --load-extension=./node_modules/nw-vue-devtools/extension`  doesn't give you an error in windows. I mean the docs for spawn say that the first argument has to be the command and the second the command arguments. 

That should work with `exec` not with `spawn`.
