### ISSUE TITLE
Add option to pass arguments to nw command

### ISSUE THREAD

**Issue by dikaso** [alex-rokabilis/nwjs-webpack-plugin#5]
Hello,

Currently we can only pass  `dirCommand` (https://github.com/noemission/nwjs-webpack-plugin/blob/master/index.js#L33) but I need to pass multiple arguments that will be parsed inside my app. Something like this:

```
new NwjsWebpackPlugin({
                 command: 'nw',
                 commandDir: [
                     path.resolve(__dirname), 
                     `--enable-logging=stderr`,
                     `--appId=${env.appId || 'myapp'}`, 
                     `--appName=${env.appName || 'myapp1'}`, 
                     `--appUrl=${env.appUrl || 'http://localhost:8080'}`, 
                     `--debugMode=${env.debugMode || true}`
                 ]
             })
```

Btw great plugin.

**Comment by noemission** [comment]
Thanks a lot for your time to write this issue. 
I am glad you like the plugin!

I added a new option with the name `args` that you could now pass to the plugin. 
It accepts an array of strings that will be passed directly to the spawned nw instance.

Now you could write:

```js
plugins: [
    new NwjsWebpackPlugin({
      command: "nw",
      commandDir: require('path').resolve(__dirname,'..', 'dist'),
      args: [
        `--enable-logging=stderr`,
        `--appId=${"myapp"}`,
        `--appName=${"myapp1"}`,
        `--appUrl=${"http://localhost:8080"}`,
        `--debugMode=${true}`
      ]
    })
  ],
``` 
I have also updated the plugin in the npm registry.

**Comment by dikaso** [comment]
Great stuff :) 

I can confirm that it works.
